// ⚠️  AUTO-GENERATED from 유형별 추천_비추천.docx — DO NOT EDIT
// Regenerate with: python3 /tmp/gsf_gen_ts.py

export type Grade = "A" | "B" | "C" | "D" | "E";

export type Skeleton = "스트레이트" | "웨이브" | "내추럴";
export type Silhouette = "어깨형" | "밸런스" | "곡선형";
export type Proportion = "롱레그" | "밸런스" | "롱토르소";
export type Frame = "슬림" | "미디엄" | "와이드";

// 상의 라벨 (코드 → "넥라인 · 핏 · 기장")
export const TOP_LABELS: Record<number, string> = {
  1: "크루넥 · 피트드 · 세미크롭",
  2: "홀터넥 · 피트드 · 세미크롭",
  3: "스쿱넥 · 피트드 · 표준",
  4: "보트넥 · 세미피트 · 표준",
  5: "스쿱넥 · 세미피트 · 표준",
  6: "크루넥 · 피트드 · 표준",
  7: "셔츠칼라 · 피트드 · 바디수트",
  8: "보트넥 · 피트드 · 표준",
  9: "V넥 · 세미피트 · 표준",
  10: "스쿱넥 · 피트드 · 표준",
  11: "스쿱넥 · 피트드 · 표준",
  12: "원숄더 · 피트드 · 세미크롭",
  13: "오프숄더 · 세미피트 · 표준",
  14: "셔츠칼라 · 세미피트 · 표준",
  15: "스쿱넥 · 세미피트 · 표준",
  16: "크루넥 · 세미피트 · 표준",
  17: "보트넥 · 피트드 · 크롭",
  18: "하트넥 · 세미피트 · 세미크롭",
  19: "오픈칼라 · 세미피트 · 표준",
  20: "V넥 · 세미피트 · 표준",
  21: "V넥 · 세미피트 · 표준",
  22: "원숄더 · 피트드 · 크롭",
  23: "크루넥 · 릴랙스드 · 롱",
  24: "원숄더 · 릴랙스드 · 표준",
  25: "보트넥 · 피트드 · 세미크롭",
  26: "V넥 · 피트드 · 표준",
  27: "스퀘어넥 · 세미피트 · 세미크롭",
  28: "모크넥 · 피트드 · 표준",
  29: "보트넥 · 피트드 · 세미크롭",
  30: "스쿱넥 · 세미피트 · 세미크롭",
  31: "V넥 · 세미피트 · 표준",
  32: "V넥 · 피트드 · 세미크롭",
  33: "V넥 · 세미피트 · 세미크롭",
  34: "스쿱넥 · 세미피트 · 크롭",
  35: "스쿱넥 · 릴랙스드 · 롱",
  36: "V넥 · 오버사이즈 · 롱",
  37: "V넥 · 오버사이즈 · 롱",
  38: "스쿱넥 · 세미피트 · 크롭",
  39: "크루넥 · 세미피트 · 세미크롭",
  40: "원숄더 · 세미피트 · 표준",
};

// 하의 라벨 (코드 → "라이즈 · 기장 · 실루엣")
export const BOTTOM_LABELS: Record<number, string> = {
  1: "로우라이즈 · 풀렝스 · 와이드",
  2: "미드라이즈 · 풀렝스 · 슬림부츠컷",
  3: "미드라이즈 · 풀렝스 · 슬림부츠컷",
  4: "미드라이즈 · 쇼츠 · 피티드",
  5: "미드라이즈 · 풀렝스 · 와이드",
  6: "미드라이즈 · 풀렝스 · 와이드",
  7: "미드라이즈 · 풀렝스 · 와이드",
  8: "미드라이즈 · 풀렝스 · 세미부츠컷",
  9: "로우라이즈 · 풀렝스 · 와이드",
  10: "미드라이즈 · 크롭 · 스키니",
  11: "로우라이즈 · 풀렝스 · 와이드",
  12: "미드라이즈 · 풀렝스 · 슬림부츠컷",
  13: "미드라이즈 · 미디 · 플레어",
  14: "미드라이즈 · 쇼츠 · 플리츠",
  15: "미드라이즈 · 맥시 · 머메이드",
  16: "로우라이즈 · 풀렝스 · 와이드",
  17: "로우라이즈 · 풀렝스 · 와이드",
  18: "로우라이즈 · 풀렝스 · 세미부츠컷",
  19: "로우라이즈 · 크롭 · 와이드",
  20: "로우라이즈 · 쇼츠 · H라인",
  21: "미드라이즈 · 마이크로쇼츠 · 스키니",
  22: "미드라이즈 · 미디 · 랩플리츠",
  23: "미드라이즈 · 맥시 · 머메이드",
  24: "미드라이즈 · 맥시 · A라인",
  25: "로우라이즈 · 쇼츠 · H라인",
};

export interface MatrixEntry {
  skeleton: Skeleton;
  silhouette: Silhouette;
  proportion: Proportion;
  frame: Frame;
  tops: Grade[];       // length 40, index = top_(i+1)
  bots: Grade[];       // length 25, index = bottom_(i+1)
  topBest: number;     // ★ 마킹된 top 인덱스 (0~39), -1 if none
  botBest: number;     // ★ 마킹된 bot 인덱스 (0~24), -1 if none
}

export const BODY_MATRIX: MatrixEntry[] = [
  {
    skeleton: "스트레이트",
    silhouette: "어깨형",
    proportion: "롱레그",
    frame: "슬림",
    tops: ["C", "D", "A", "C", "A", "B", "B", "C", "A", "A", "A", "D", "C", "B", "A", "B", "D", "B", "B", "A", "A", "D", "C", "D", "D", "A", "D", "B", "D", "B", "A", "B", "B", "B", "B", "C", "C", "B", "C", "C"],
    bots: ["C", "B", "B", "B", "C", "C", "C", "B", "C", "C", "C", "B", "A", "B", "B", "C", "C", "B", "B", "B", "C", "B", "B", "A", "B"],
    topBest: 2,
    botBest: 12,
  },
  {
    skeleton: "스트레이트",
    silhouette: "어깨형",
    proportion: "롱레그",
    frame: "미디엄",
    tops: ["C", "D", "A", "C", "A", "B", "C", "C", "A", "A", "A", "D", "C", "B", "A", "B", "D", "B", "B", "A", "A", "D", "C", "D", "D", "A", "D", "B", "D", "B", "A", "B", "B", "B", "B", "B", "B", "B", "C", "C"],
    bots: ["B", "B", "B", "C", "B", "B", "B", "B", "B", "C", "B", "B", "A", "B", "B", "B", "B", "B", "A", "C", "C", "B", "B", "A", "C"],
    topBest: 2,
    botBest: 12,
  },
  {
    skeleton: "스트레이트",
    silhouette: "어깨형",
    proportion: "롱레그",
    frame: "와이드",
    tops: ["D", "E", "C", "D", "B", "D", "D", "E", "B", "C", "C", "E", "D", "B", "B", "C", "E", "C", "B", "B", "B", "E", "B", "D", "E", "C", "E", "D", "E", "C", "B", "C", "C", "C", "A", "A", "A", "C", "D", "D"],
    bots: ["A", "C", "C", "D", "A", "A", "A", "B", "A", "D", "A", "C", "A", "B", "B", "A", "A", "B", "A", "C", "D", "B", "B", "A", "C"],
    topBest: 34,
    botBest: 12,
  },
  {
    skeleton: "스트레이트",
    silhouette: "어깨형",
    proportion: "밸런스",
    frame: "슬림",
    tops: ["B", "C", "A", "C", "A", "B", "B", "C", "A", "A", "A", "C", "C", "B", "A", "B", "C", "A", "B", "A", "A", "C", "C", "D", "C", "A", "C", "B", "C", "A", "A", "A", "A", "A", "B", "C", "C", "A", "B", "C"],
    bots: ["C", "B", "B", "C", "C", "C", "C", "B", "C", "C", "C", "B", "B", "B", "B", "C", "C", "B", "C", "C", "C", "B", "B", "A", "C"],
    topBest: 2,
    botBest: 23,
  },
  {
    skeleton: "스트레이트",
    silhouette: "어깨형",
    proportion: "밸런스",
    frame: "미디엄",
    tops: ["B", "C", "A", "C", "A", "B", "B", "C", "A", "A", "A", "C", "C", "B", "A", "B", "C", "A", "B", "A", "A", "C", "C", "D", "C", "A", "C", "B", "C", "A", "A", "A", "A", "A", "B", "B", "B", "A", "B", "C"],
    bots: ["B", "B", "B", "C", "B", "B", "B", "B", "B", "C", "B", "B", "B", "B", "B", "B", "B", "B", "B", "C", "C", "B", "B", "A", "C"],
    topBest: 2,
    botBest: 23,
  },
  {
    skeleton: "스트레이트",
    silhouette: "어깨형",
    proportion: "밸런스",
    frame: "와이드",
    tops: ["D", "E", "C", "D", "B", "D", "C", "E", "B", "C", "C", "E", "D", "B", "B", "C", "E", "B", "B", "B", "B", "E", "C", "D", "E", "C", "D", "D", "E", "B", "B", "C", "B", "B", "B", "B", "B", "B", "C", "D"],
    bots: ["A", "C", "C", "D", "A", "A", "A", "B", "A", "E", "A", "C", "A", "C", "B", "A", "A", "B", "A", "C", "E", "C", "B", "A", "C"],
    topBest: 34,
    botBest: 23,
  },
  {
    skeleton: "스트레이트",
    silhouette: "어깨형",
    proportion: "롱토르소",
    frame: "슬림",
    tops: ["B", "C", "A", "C", "A", "B", "A", "C", "A", "A", "A", "C", "C", "B", "A", "B", "C", "A", "B", "A", "A", "C", "D", "E", "C", "A", "C", "B", "C", "A", "A", "A", "A", "A", "C", "D", "D", "A", "B", "C"],
    bots: ["C", "B", "B", "C", "C", "C", "C", "B", "C", "C", "C", "B", "B", "C", "B", "C", "C", "C", "D", "D", "C", "C", "B", "A", "D"],
    topBest: 17,
    botBest: 23,
  },
  {
    skeleton: "스트레이트",
    silhouette: "어깨형",
    proportion: "롱토르소",
    frame: "미디엄",
    tops: ["B", "C", "B", "D", "B", "C", "B", "D", "B", "B", "B", "C", "D", "B", "B", "C", "C", "A", "B", "B", "B", "C", "D", "D", "C", "B", "C", "C", "C", "A", "B", "A", "A", "A", "C", "C", "C", "A", "B", "D"],
    bots: ["B", "B", "B", "C", "B", "B", "B", "B", "B", "D", "B", "B", "B", "C", "B", "B", "B", "C", "C", "D", "D", "C", "B", "A", "D"],
    topBest: 17,
    botBest: 23,
  },
  {
    skeleton: "스트레이트",
    silhouette: "어깨형",
    proportion: "롱토르소",
    frame: "와이드",
    tops: ["C", "D", "C", "D", "B", "D", "C", "E", "B", "C", "C", "D", "D", "C", "B", "C", "D", "B", "C", "B", "B", "D", "D", "D", "D", "C", "D", "D", "D", "B", "B", "B", "B", "B", "C", "C", "C", "B", "C", "D"],
    bots: ["B", "C", "C", "E", "A", "A", "A", "B", "B", "E", "B", "C", "B", "C", "B", "B", "B", "C", "B", "D", "E", "C", "B", "A", "D"],
    topBest: 17,
    botBest: 23,
  },
  {
    skeleton: "스트레이트",
    silhouette: "밸런스",
    proportion: "롱레그",
    frame: "슬림",
    tops: ["B", "B", "B", "A", "B", "B", "B", "A", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "C", "C", "C", "B", "B", "B", "B", "B", "B", "B", "B", "B", "C", "C", "C", "C", "C", "B", "B"],
    bots: ["C", "B", "B", "A", "C", "C", "C", "B", "C", "A", "C", "B", "B", "B", "B", "C", "C", "B", "C", "A", "A", "B", "B", "B", "A"],
    topBest: 3,
    botBest: 3,
  },
  {
    skeleton: "스트레이트",
    silhouette: "밸런스",
    proportion: "롱레그",
    frame: "미디엄",
    tops: ["C", "C", "B", "A", "B", "B", "C", "A", "B", "B", "B", "C", "B", "B", "B", "B", "B", "C", "B", "B", "B", "C", "B", "B", "B", "B", "B", "B", "B", "C", "B", "C", "C", "C", "B", "B", "B", "C", "C", "B"],
    bots: ["B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B"],
    topBest: 3,
    botBest: 3,
  },
  {
    skeleton: "스트레이트",
    silhouette: "밸런스",
    proportion: "롱레그",
    frame: "와이드",
    tops: ["D", "D", "C", "B", "B", "C", "D", "C", "B", "C", "C", "D", "C", "B", "B", "B", "D", "C", "B", "B", "B", "D", "B", "B", "C", "C", "C", "C", "C", "C", "B", "D", "C", "C", "B", "B", "B", "C", "C", "B"],
    bots: ["B", "C", "C", "C", "B", "B", "B", "B", "B", "C", "B", "C", "A", "B", "B", "B", "B", "B", "A", "B", "C", "B", "B", "B", "B"],
    topBest: 22,
    botBest: 12,
  },
  {
    skeleton: "스트레이트",
    silhouette: "밸런스",
    proportion: "밸런스",
    frame: "슬림",
    tops: ["B", "B", "B", "A", "B", "B", "B", "A", "B", "B", "B", "B", "B", "B", "B", "B", "A", "B", "B", "B", "B", "B", "C", "C", "A", "B", "A", "B", "A", "B", "B", "B", "B", "B", "C", "D", "D", "B", "B", "B"],
    bots: ["C", "B", "B", "B", "C", "C", "C", "B", "C", "B", "C", "B", "B", "B", "B", "C", "C", "B", "C", "B", "B", "B", "B", "B", "B"],
    topBest: 3,
    botBest: 1,
  },
  {
    skeleton: "스트레이트",
    silhouette: "밸런스",
    proportion: "밸런스",
    frame: "미디엄",
    tops: ["B", "B", "B", "A", "B", "B", "B", "A", "B", "B", "B", "B", "B", "B", "B", "B", "A", "B", "B", "B", "B", "B", "B", "B", "A", "B", "A", "B", "A", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B"],
    bots: ["B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B"],
    topBest: 3,
    botBest: 1,
  },
  {
    skeleton: "스트레이트",
    silhouette: "밸런스",
    proportion: "밸런스",
    frame: "와이드",
    tops: ["C", "C", "C", "B", "B", "C", "C", "C", "B", "C", "C", "C", "C", "B", "B", "B", "C", "B", "B", "B", "B", "C", "B", "B", "C", "C", "B", "C", "C", "B", "B", "C", "B", "B", "B", "B", "B", "B", "B", "B"],
    bots: ["B", "C", "C", "C", "B", "B", "B", "B", "B", "C", "B", "C", "B", "C", "B", "B", "B", "B", "B", "B", "C", "C", "B", "B", "B"],
    topBest: 3,
    botBest: 23,
  },
  {
    skeleton: "스트레이트",
    silhouette: "밸런스",
    proportion: "롱토르소",
    frame: "슬림",
    tops: ["A", "A", "B", "A", "B", "B", "A", "A", "B", "B", "B", "A", "B", "B", "B", "B", "A", "A", "B", "B", "B", "A", "D", "C", "A", "B", "A", "B", "A", "A", "B", "A", "A", "A", "D", "E", "E", "A", "A", "B"],
    bots: ["D", "B", "B", "B", "C", "C", "C", "B", "D", "B", "D", "B", "C", "C", "B", "D", "D", "C", "D", "C", "B", "C", "B", "B", "C"],
    topBest: 16,
    botBest: 1,
  },
  {
    skeleton: "스트레이트",
    silhouette: "밸런스",
    proportion: "롱토르소",
    frame: "미디엄",
    tops: ["B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "C", "B", "B", "B", "A", "B", "B", "B", "B", "B", "D", "C", "A", "B", "A", "B", "A", "B", "B", "B", "B", "B", "D", "D", "D", "B", "B", "B"],
    bots: ["C", "B", "B", "B", "B", "B", "B", "B", "C", "B", "C", "B", "C", "C", "B", "C", "C", "C", "C", "C", "B", "C", "B", "B", "C"],
    topBest: 16,
    botBest: 1,
  },
  {
    skeleton: "스트레이트",
    silhouette: "밸런스",
    proportion: "롱토르소",
    frame: "와이드",
    tops: ["C", "C", "D", "B", "C", "D", "C", "C", "C", "D", "D", "C", "C", "C", "C", "C", "B", "B", "C", "C", "C", "C", "C", "B", "B", "D", "B", "D", "B", "B", "C", "C", "B", "B", "C", "C", "C", "B", "B", "C"],
    bots: ["B", "C", "C", "D", "B", "B", "B", "B", "B", "D", "B", "C", "B", "C", "B", "B", "B", "C", "C", "C", "D", "C", "B", "B", "C"],
    topBest: 26,
    botBest: 23,
  },
  {
    skeleton: "스트레이트",
    silhouette: "곡선형",
    proportion: "롱레그",
    frame: "슬림",
    tops: ["B", "C", "B", "B", "B", "B", "B", "B", "A", "B", "B", "C", "B", "B", "B", "B", "C", "B", "B", "A", "A", "C", "C", "C", "C", "A", "C", "C", "C", "B", "A", "B", "B", "C", "C", "C", "C", "C", "B", "B"],
    bots: ["E", "B", "B", "A", "E", "E", "E", "B", "E", "A", "E", "B", "B", "B", "B", "E", "E", "B", "D", "A", "A", "B", "B", "B", "A"],
    topBest: 8,
    botBest: 3,
  },
  {
    skeleton: "스트레이트",
    silhouette: "곡선형",
    proportion: "롱레그",
    frame: "미디엄",
    tops: ["C", "C", "B", "B", "B", "B", "C", "B", "A", "B", "B", "C", "B", "B", "B", "B", "C", "B", "B", "A", "A", "C", "B", "C", "C", "A", "C", "C", "C", "C", "A", "B", "B", "C", "B", "B", "B", "C", "C", "B"],
    bots: ["D", "B", "B", "B", "D", "D", "D", "B", "D", "B", "D", "B", "B", "B", "B", "D", "D", "B", "C", "B", "B", "B", "B", "B", "B"],
    topBest: 8,
    botBest: 3,
  },
  {
    skeleton: "스트레이트",
    silhouette: "곡선형",
    proportion: "롱레그",
    frame: "와이드",
    tops: ["D", "D", "C", "C", "B", "C", "D", "D", "B", "C", "C", "D", "C", "B", "B", "B", "E", "C", "B", "B", "B", "E", "B", "C", "D", "C", "D", "E", "D", "C", "B", "C", "C", "C", "B", "A", "A", "C", "C", "C"],
    bots: ["C", "C", "C", "C", "C", "C", "C", "B", "C", "C", "C", "C", "A", "C", "B", "C", "C", "B", "C", "B", "C", "C", "B", "B", "B"],
    topBest: 35,
    botBest: 12,
  },
  {
    skeleton: "스트레이트",
    silhouette: "곡선형",
    proportion: "밸런스",
    frame: "슬림",
    tops: ["B", "B", "B", "B", "B", "B", "B", "B", "A", "B", "B", "B", "B", "B", "B", "B", "B", "A", "B", "A", "A", "B", "C", "C", "B", "A", "B", "C", "B", "B", "A", "A", "A", "B", "C", "C", "C", "B", "B", "B"],
    bots: ["E", "B", "B", "B", "E", "E", "E", "B", "E", "B", "E", "B", "B", "C", "B", "E", "E", "B", "E", "B", "B", "C", "B", "B", "B"],
    topBest: 8,
    botBest: 1,
  },
  {
    skeleton: "스트레이트",
    silhouette: "곡선형",
    proportion: "밸런스",
    frame: "미디엄",
    tops: ["B", "B", "B", "B", "B", "B", "B", "B", "A", "B", "B", "B", "B", "B", "B", "B", "B", "A", "B", "A", "A", "B", "B", "C", "B", "A", "B", "C", "B", "B", "A", "A", "A", "B", "B", "B", "B", "B", "B", "B"],
    bots: ["D", "B", "B", "B", "D", "D", "D", "B", "D", "B", "D", "B", "B", "C", "B", "D", "D", "B", "D", "B", "B", "C", "B", "B", "B"],
    topBest: 8,
    botBest: 1,
  },
  {
    skeleton: "스트레이트",
    silhouette: "곡선형",
    proportion: "밸런스",
    frame: "와이드",
    tops: ["C", "D", "C", "C", "B", "C", "C", "D", "B", "C", "C", "D", "C", "B", "B", "B", "D", "B", "B", "B", "B", "D", "B", "C", "D", "C", "C", "E", "D", "B", "B", "C", "B", "B", "B", "B", "B", "B", "B", "C"],
    bots: ["C", "C", "C", "C", "C", "C", "C", "B", "C", "C", "C", "C", "B", "C", "B", "C", "C", "B", "C", "B", "C", "C", "B", "B", "B"],
    topBest: 35,
    botBest: 23,
  },
  {
    skeleton: "스트레이트",
    silhouette: "곡선형",
    proportion: "롱토르소",
    frame: "슬림",
    tops: ["A", "B", "B", "B", "B", "B", "A", "B", "A", "B", "B", "B", "B", "B", "B", "B", "B", "A", "B", "A", "A", "B", "D", "D", "B", "A", "B", "C", "B", "A", "A", "A", "A", "A", "D", "D", "D", "A", "A", "B"],
    bots: ["E", "B", "B", "B", "E", "E", "E", "B", "E", "B", "E", "B", "C", "C", "B", "E", "E", "C", "E", "C", "B", "C", "B", "B", "C"],
    topBest: 17,
    botBest: 1,
  },
  {
    skeleton: "스트레이트",
    silhouette: "곡선형",
    proportion: "롱토르소",
    frame: "미디엄",
    tops: ["B", "B", "B", "C", "B", "B", "B", "C", "B", "B", "B", "B", "C", "B", "B", "B", "B", "A", "B", "B", "B", "B", "D", "C", "B", "B", "B", "D", "B", "B", "B", "A", "A", "B", "D", "C", "C", "B", "B", "C"],
    bots: ["D", "B", "B", "B", "D", "D", "D", "B", "D", "B", "D", "B", "C", "C", "B", "D", "D", "C", "E", "C", "B", "C", "B", "B", "C"],
    topBest: 17,
    botBest: 1,
  },
  {
    skeleton: "스트레이트",
    silhouette: "곡선형",
    proportion: "롱토르소",
    frame: "와이드",
    tops: ["C", "C", "D", "C", "C", "D", "C", "D", "B", "D", "D", "C", "C", "C", "C", "C", "C", "B", "C", "B", "B", "C", "C", "C", "C", "C", "C", "E", "C", "B", "B", "B", "B", "B", "C", "C", "C", "B", "B", "C"],
    bots: ["D", "C", "C", "D", "C", "C", "C", "B", "D", "D", "D", "C", "B", "C", "B", "D", "D", "C", "D", "C", "D", "C", "B", "B", "C"],
    topBest: 17,
    botBest: 23,
  },
  {
    skeleton: "내추럴",
    silhouette: "어깨형",
    proportion: "롱레그",
    frame: "슬림",
    tops: ["C", "D", "B", "C", "A", "C", "C", "D", "A", "B", "B", "D", "C", "B", "A", "B", "E", "B", "B", "A", "A", "E", "C", "D", "D", "B", "D", "C", "D", "B", "A", "B", "B", "B", "B", "B", "B", "B", "C", "C"],
    bots: ["B", "B", "B", "B", "B", "B", "B", "B", "B", "C", "B", "B", "A", "B", "B", "B", "B", "B", "B", "B", "C", "B", "B", "A", "B"],
    topBest: 4,
    botBest: 12,
  },
  {
    skeleton: "내추럴",
    silhouette: "어깨형",
    proportion: "롱레그",
    frame: "미디엄",
    tops: ["D", "E", "B", "C", "A", "C", "C", "D", "A", "B", "B", "E", "C", "B", "A", "B", "E", "B", "B", "A", "A", "E", "B", "C", "E", "B", "D", "C", "E", "B", "A", "C", "B", "B", "A", "A", "A", "B", "C", "C"],
    bots: ["A", "B", "B", "C", "A", "A", "A", "B", "A", "C", "A", "B", "A", "B", "B", "A", "A", "B", "A", "C", "C", "B", "B", "A", "C"],
    topBest: 34,
    botBest: 12,
  },
  {
    skeleton: "내추럴",
    silhouette: "어깨형",
    proportion: "롱레그",
    frame: "와이드",
    tops: ["E", "E", "C", "D", "B", "D", "D", "E", "B", "C", "C", "E", "D", "B", "B", "C", "E", "C", "B", "B", "B", "E", "B", "C", "E", "C", "E", "D", "E", "C", "B", "D", "C", "C", "A", "A", "A", "C", "D", "D"],
    bots: ["A", "C", "C", "D", "A", "A", "A", "C", "A", "E", "A", "C", "A", "B", "A", "A", "A", "C", "A", "C", "E", "B", "A", "A", "C"],
    topBest: 34,
    botBest: 12,
  },
  {
    skeleton: "내추럴",
    silhouette: "어깨형",
    proportion: "밸런스",
    frame: "슬림",
    tops: ["C", "D", "B", "C", "A", "C", "B", "D", "A", "B", "B", "D", "C", "B", "A", "B", "D", "A", "B", "A", "A", "D", "C", "D", "D", "B", "C", "C", "D", "A", "A", "B", "A", "A", "B", "C", "C", "A", "B", "C"],
    bots: ["B", "B", "B", "C", "B", "B", "B", "B", "B", "C", "B", "B", "A", "B", "B", "B", "B", "B", "B", "C", "C", "B", "B", "A", "C"],
    topBest: 4,
    botBest: 12,
  },
  {
    skeleton: "내추럴",
    silhouette: "어깨형",
    proportion: "밸런스",
    frame: "미디엄",
    tops: ["C", "D", "B", "C", "A", "C", "B", "D", "A", "B", "B", "D", "C", "B", "A", "B", "D", "A", "B", "A", "A", "D", "B", "C", "D", "B", "C", "C", "D", "A", "A", "B", "A", "A", "A", "A", "A", "A", "B", "C"],
    bots: ["A", "B", "B", "C", "A", "A", "A", "B", "A", "D", "A", "B", "A", "B", "B", "A", "A", "B", "A", "C", "D", "B", "B", "A", "C"],
    topBest: 4,
    botBest: 0,
  },
  {
    skeleton: "내추럴",
    silhouette: "어깨형",
    proportion: "밸런스",
    frame: "와이드",
    tops: ["D", "E", "C", "D", "B", "D", "D", "E", "B", "C", "C", "E", "D", "B", "B", "C", "E", "B", "B", "B", "B", "E", "B", "C", "E", "C", "D", "D", "E", "B", "B", "C", "B", "B", "A", "A", "A", "B", "C", "D"],
    bots: ["A", "C", "C", "E", "A", "A", "A", "C", "A", "E", "A", "C", "A", "C", "A", "A", "A", "C", "A", "D", "E", "C", "A", "A", "D"],
    topBest: 34,
    botBest: 0,
  },
  {
    skeleton: "내추럴",
    silhouette: "어깨형",
    proportion: "롱토르소",
    frame: "슬림",
    tops: ["B", "C", "B", "C", "A", "C", "B", "D", "A", "B", "B", "C", "C", "B", "A", "B", "C", "A", "B", "A", "A", "C", "D", "D", "C", "B", "C", "C", "C", "A", "A", "A", "A", "A", "C", "D", "D", "A", "B", "C"],
    bots: ["C", "B", "B", "C", "B", "B", "B", "B", "C", "D", "C", "B", "B", "C", "B", "C", "C", "C", "C", "D", "D", "C", "B", "A", "D"],
    topBest: 17,
    botBest: 23,
  },
  {
    skeleton: "내추럴",
    silhouette: "어깨형",
    proportion: "롱토르소",
    frame: "미디엄",
    tops: ["C", "D", "B", "D", "B", "C", "B", "D", "B", "B", "B", "D", "D", "B", "B", "C", "D", "A", "B", "B", "B", "D", "C", "D", "D", "B", "C", "C", "D", "A", "B", "B", "A", "A", "B", "B", "B", "A", "B", "D"],
    bots: ["B", "B", "B", "D", "A", "A", "A", "B", "B", "D", "B", "B", "B", "C", "B", "B", "B", "C", "B", "D", "D", "C", "B", "A", "D"],
    topBest: 17,
    botBest: 4,
  },
  {
    skeleton: "내추럴",
    silhouette: "어깨형",
    proportion: "롱토르소",
    frame: "와이드",
    tops: ["D", "E", "D", "D", "B", "E", "C", "E", "B", "D", "D", "E", "D", "C", "B", "C", "E", "B", "C", "B", "B", "E", "C", "C", "E", "D", "D", "E", "E", "B", "B", "C", "B", "B", "B", "B", "B", "B", "C", "D"],
    bots: ["B", "C", "C", "E", "A", "A", "A", "C", "B", "E", "B", "C", "A", "C", "A", "B", "B", "C", "B", "E", "E", "C", "A", "A", "E"],
    topBest: 17,
    botBest: 4,
  },
  {
    skeleton: "내추럴",
    silhouette: "밸런스",
    proportion: "롱레그",
    frame: "슬림",
    tops: ["C", "C", "B", "A", "B", "B", "C", "B", "B", "B", "B", "C", "B", "B", "B", "B", "C", "B", "B", "B", "B", "C", "B", "B", "B", "B", "B", "B", "B", "B", "B", "C", "B", "C", "B", "C", "C", "C", "B", "B"],
    bots: ["C", "B", "B", "A", "C", "C", "C", "B", "C", "A", "C", "B", "B", "B", "B", "C", "C", "B", "B", "A", "A", "B", "B", "B", "A"],
    topBest: 3,
    botBest: 3,
  },
  {
    skeleton: "내추럴",
    silhouette: "밸런스",
    proportion: "롱레그",
    frame: "미디엄",
    tops: ["C", "C", "B", "A", "B", "B", "C", "B", "B", "B", "B", "C", "B", "B", "B", "B", "C", "C", "B", "B", "B", "D", "B", "B", "C", "B", "B", "B", "C", "C", "B", "C", "C", "C", "B", "B", "B", "C", "C", "B"],
    bots: ["B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B"],
    topBest: 3,
    botBest: 12,
  },
  {
    skeleton: "내추럴",
    silhouette: "밸런스",
    proportion: "롱레그",
    frame: "와이드",
    tops: ["D", "D", "D", "B", "B", "D", "D", "C", "B", "D", "D", "D", "C", "B", "B", "B", "D", "C", "B", "B", "B", "E", "A", "B", "D", "D", "C", "D", "D", "C", "B", "D", "C", "C", "A", "A", "A", "C", "C", "B"],
    bots: ["B", "C", "C", "C", "B", "B", "B", "C", "B", "C", "B", "C", "A", "B", "B", "B", "B", "C", "A", "B", "C", "B", "B", "B", "B"],
    topBest: 22,
    botBest: 12,
  },
  {
    skeleton: "내추럴",
    silhouette: "밸런스",
    proportion: "밸런스",
    frame: "슬림",
    tops: ["B", "B", "B", "A", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "A", "B", "B", "B", "B", "B", "B", "B", "B", "C", "C", "B", "B", "B"],
    bots: ["C", "B", "B", "B", "C", "C", "C", "B", "C", "B", "C", "B", "B", "B", "B", "C", "C", "B", "C", "B", "B", "B", "B", "B", "B"],
    topBest: 3,
    botBest: 1,
  },
  {
    skeleton: "내추럴",
    silhouette: "밸런스",
    proportion: "밸런스",
    frame: "미디엄",
    tops: ["B", "B", "B", "A", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "A", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B"],
    bots: ["B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B"],
    topBest: 3,
    botBest: 0,
  },
  {
    skeleton: "내추럴",
    silhouette: "밸런스",
    proportion: "밸런스",
    frame: "와이드",
    tops: ["D", "D", "D", "B", "B", "D", "D", "C", "B", "D", "D", "D", "C", "B", "B", "B", "C", "B", "B", "B", "B", "D", "B", "B", "C", "D", "B", "D", "C", "B", "B", "D", "B", "B", "B", "B", "B", "B", "B", "B"],
    bots: ["B", "C", "C", "D", "B", "B", "B", "C", "B", "D", "B", "C", "B", "C", "B", "B", "B", "C", "B", "C", "D", "C", "B", "B", "C"],
    topBest: 22,
    botBest: 0,
  },
  {
    skeleton: "내추럴",
    silhouette: "밸런스",
    proportion: "롱토르소",
    frame: "슬림",
    tops: ["B", "B", "B", "A", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "A", "A", "B", "B", "B", "B", "C", "C", "A", "B", "A", "B", "A", "A", "B", "B", "A", "A", "C", "D", "D", "A", "A", "B"],
    bots: ["C", "B", "B", "B", "C", "C", "C", "B", "C", "B", "C", "B", "B", "C", "B", "C", "C", "C", "D", "C", "B", "C", "B", "B", "C"],
    topBest: 26,
    botBest: 1,
  },
  {
    skeleton: "내추럴",
    silhouette: "밸런스",
    proportion: "롱토르소",
    frame: "미디엄",
    tops: ["B", "B", "C", "B", "B", "C", "B", "B", "B", "C", "C", "B", "C", "B", "B", "B", "B", "B", "B", "B", "B", "B", "C", "B", "B", "C", "A", "C", "B", "B", "B", "B", "B", "B", "C", "C", "C", "B", "B", "B"],
    bots: ["C", "B", "B", "C", "B", "B", "B", "B", "C", "C", "C", "B", "B", "C", "B", "C", "C", "C", "C", "C", "C", "C", "B", "B", "C"],
    topBest: 26,
    botBest: 4,
  },
  {
    skeleton: "내추럴",
    silhouette: "밸런스",
    proportion: "롱토르소",
    frame: "와이드",
    tops: ["C", "C", "D", "B", "C", "D", "C", "D", "C", "D", "D", "C", "C", "C", "C", "C", "C", "B", "C", "C", "C", "C", "C", "B", "C", "D", "B", "D", "C", "B", "C", "C", "B", "B", "C", "C", "C", "B", "B", "C"],
    bots: ["B", "C", "C", "D", "B", "B", "B", "C", "B", "D", "B", "C", "B", "C", "B", "B", "B", "C", "C", "D", "D", "C", "B", "B", "D"],
    topBest: 26,
    botBest: 4,
  },
  {
    skeleton: "내추럴",
    silhouette: "곡선형",
    proportion: "롱레그",
    frame: "슬림",
    tops: ["C", "C", "B", "B", "B", "B", "C", "C", "A", "B", "B", "C", "B", "B", "B", "B", "D", "B", "B", "A", "A", "D", "B", "C", "C", "B", "C", "D", "C", "B", "A", "B", "B", "C", "B", "B", "B", "C", "B", "B"],
    bots: ["D", "B", "B", "A", "D", "D", "D", "B", "D", "A", "D", "B", "B", "B", "B", "D", "D", "B", "D", "A", "A", "B", "B", "B", "A"],
    topBest: 8,
    botBest: 3,
  },
  {
    skeleton: "내추럴",
    silhouette: "곡선형",
    proportion: "롱레그",
    frame: "미디엄",
    tops: ["C", "D", "B", "B", "B", "B", "C", "C", "A", "B", "B", "D", "B", "B", "B", "B", "D", "B", "B", "A", "A", "D", "B", "B", "D", "B", "C", "D", "D", "C", "A", "C", "B", "C", "B", "A", "A", "C", "C", "B"],
    bots: ["C", "B", "B", "B", "C", "C", "C", "B", "C", "B", "C", "B", "B", "B", "B", "C", "C", "B", "C", "B", "B", "B", "B", "B", "B"],
    topBest: 35,
    botBest: 12,
  },
  {
    skeleton: "내추럴",
    silhouette: "곡선형",
    proportion: "롱레그",
    frame: "와이드",
    tops: ["D", "E", "D", "C", "B", "D", "D", "D", "B", "D", "D", "E", "C", "B", "B", "B", "E", "C", "B", "B", "B", "E", "A", "B", "E", "C", "D", "E", "E", "C", "B", "D", "C", "C", "A", "A", "A", "C", "C", "C"],
    bots: ["C", "C", "C", "C", "C", "C", "C", "C", "C", "C", "C", "C", "A", "C", "B", "C", "C", "C", "C", "B", "C", "C", "B", "B", "B"],
    topBest: 35,
    botBest: 12,
  },
  {
    skeleton: "내추럴",
    silhouette: "곡선형",
    proportion: "밸런스",
    frame: "슬림",
    tops: ["B", "C", "B", "B", "B", "B", "B", "C", "A", "B", "B", "C", "B", "B", "B", "B", "C", "A", "B", "A", "A", "C", "B", "C", "C", "B", "B", "D", "C", "B", "A", "B", "A", "B", "B", "C", "C", "B", "B", "B"],
    bots: ["D", "B", "B", "B", "D", "D", "D", "B", "D", "B", "D", "B", "B", "C", "B", "D", "D", "B", "D", "B", "B", "C", "B", "B", "B"],
    topBest: 8,
    botBest: 1,
  },
  {
    skeleton: "내추럴",
    silhouette: "곡선형",
    proportion: "밸런스",
    frame: "미디엄",
    tops: ["B", "C", "B", "B", "B", "B", "B", "C", "A", "B", "B", "C", "B", "B", "B", "B", "C", "A", "B", "A", "A", "C", "B", "B", "C", "B", "B", "D", "C", "B", "A", "B", "A", "B", "B", "A", "A", "B", "B", "B"],
    bots: ["C", "B", "B", "B", "C", "C", "C", "B", "C", "B", "C", "B", "B", "C", "B", "C", "C", "B", "C", "B", "B", "C", "B", "B", "B"],
    topBest: 8,
    botBest: 12,
  },
  {
    skeleton: "내추럴",
    silhouette: "곡선형",
    proportion: "밸런스",
    frame: "와이드",
    tops: ["D", "D", "D", "C", "B", "D", "D", "D", "B", "D", "D", "D", "C", "B", "B", "B", "D", "B", "B", "B", "B", "D", "B", "B", "D", "C", "C", "E", "D", "B", "B", "C", "B", "B", "B", "A", "A", "B", "B", "C"],
    bots: ["C", "C", "C", "D", "C", "C", "C", "C", "C", "D", "C", "C", "B", "C", "B", "C", "C", "C", "C", "C", "D", "C", "B", "B", "C"],
    topBest: 35,
    botBest: 12,
  },
  {
    skeleton: "내추럴",
    silhouette: "곡선형",
    proportion: "롱토르소",
    frame: "슬림",
    tops: ["B", "B", "B", "B", "B", "B", "B", "C", "A", "B", "B", "B", "B", "B", "B", "B", "B", "A", "B", "A", "A", "B", "C", "C", "B", "B", "B", "D", "B", "A", "A", "A", "A", "A", "C", "D", "D", "A", "A", "B"],
    bots: ["E", "B", "B", "B", "D", "D", "D", "B", "E", "B", "E", "B", "B", "C", "B", "E", "E", "C", "E", "C", "B", "C", "B", "B", "C"],
    topBest: 17,
    botBest: 1,
  },
  {
    skeleton: "내추럴",
    silhouette: "곡선형",
    proportion: "롱토르소",
    frame: "미디엄",
    tops: ["B", "C", "C", "C", "B", "C", "B", "C", "B", "C", "C", "C", "C", "B", "B", "B", "C", "A", "B", "B", "B", "C", "C", "C", "C", "B", "B", "D", "C", "B", "B", "B", "A", "B", "C", "B", "B", "B", "B", "C"],
    bots: ["D", "B", "B", "C", "C", "C", "C", "B", "D", "C", "D", "B", "B", "C", "B", "D", "D", "C", "D", "C", "C", "C", "B", "B", "C"],
    topBest: 17,
    botBest: 23,
  },
  {
    skeleton: "내추럴",
    silhouette: "곡선형",
    proportion: "롱토르소",
    frame: "와이드",
    tops: ["C", "D", "D", "C", "C", "D", "C", "E", "B", "D", "D", "D", "C", "C", "C", "C", "D", "B", "C", "B", "B", "D", "C", "B", "D", "D", "C", "E", "D", "B", "B", "C", "B", "B", "C", "B", "B", "B", "B", "C"],
    bots: ["D", "C", "C", "D", "C", "C", "C", "C", "D", "D", "D", "C", "B", "C", "B", "D", "D", "C", "D", "D", "D", "C", "B", "B", "D"],
    topBest: 17,
    botBest: 23,
  },
  {
    skeleton: "웨이브",
    silhouette: "어깨형",
    proportion: "롱레그",
    frame: "슬림",
    tops: ["C", "D", "A", "C", "A", "B", "B", "C", "A", "A", "A", "D", "C", "B", "A", "B", "D", "B", "B", "A", "A", "D", "C", "D", "D", "A", "D", "B", "D", "B", "A", "B", "B", "B", "B", "C", "C", "B", "C", "C"],
    bots: ["C", "B", "B", "B", "C", "C", "C", "B", "C", "C", "C", "B", "A", "B", "A", "C", "C", "B", "C", "B", "C", "B", "A", "B", "B"],
    topBest: 2,
    botBest: 12,
  },
  {
    skeleton: "웨이브",
    silhouette: "어깨형",
    proportion: "롱레그",
    frame: "미디엄",
    tops: ["C", "D", "A", "C", "A", "B", "C", "C", "A", "A", "A", "D", "C", "B", "A", "B", "D", "B", "B", "A", "A", "D", "B", "D", "D", "A", "D", "B", "D", "B", "A", "B", "B", "B", "A", "B", "B", "B", "C", "C"],
    bots: ["B", "B", "B", "C", "B", "B", "B", "B", "B", "C", "B", "B", "A", "B", "A", "B", "B", "B", "B", "C", "C", "B", "A", "B", "C"],
    topBest: 34,
    botBest: 12,
  },
  {
    skeleton: "웨이브",
    silhouette: "어깨형",
    proportion: "롱레그",
    frame: "와이드",
    tops: ["D", "E", "C", "D", "B", "D", "D", "E", "B", "C", "C", "E", "D", "B", "B", "C", "E", "C", "B", "B", "B", "E", "B", "C", "E", "C", "E", "D", "E", "C", "B", "C", "C", "C", "A", "A", "A", "C", "D", "D"],
    bots: ["B", "C", "C", "D", "B", "B", "B", "C", "B", "D", "B", "C", "A", "B", "A", "B", "B", "C", "A", "C", "D", "B", "A", "A", "C"],
    topBest: 34,
    botBest: 12,
  },
  {
    skeleton: "웨이브",
    silhouette: "어깨형",
    proportion: "밸런스",
    frame: "슬림",
    tops: ["B", "C", "A", "C", "A", "B", "B", "C", "A", "A", "A", "C", "C", "B", "A", "B", "C", "A", "B", "A", "A", "C", "C", "D", "C", "A", "C", "B", "C", "A", "A", "A", "A", "A", "B", "C", "C", "A", "B", "C"],
    bots: ["C", "B", "B", "C", "C", "C", "C", "B", "C", "C", "C", "B", "A", "B", "A", "C", "C", "B", "C", "C", "C", "B", "A", "B", "C"],
    topBest: 2,
    botBest: 12,
  },
  {
    skeleton: "웨이브",
    silhouette: "어깨형",
    proportion: "밸런스",
    frame: "미디엄",
    tops: ["B", "C", "A", "C", "A", "B", "B", "C", "A", "A", "A", "C", "C", "B", "A", "B", "C", "A", "B", "A", "A", "C", "C", "D", "C", "A", "C", "B", "C", "A", "A", "A", "A", "A", "B", "B", "B", "A", "B", "C"],
    bots: ["B", "B", "B", "C", "B", "B", "B", "B", "B", "C", "B", "B", "A", "B", "A", "B", "B", "B", "B", "C", "C", "B", "A", "B", "C"],
    topBest: 2,
    botBest: 12,
  },
  {
    skeleton: "웨이브",
    silhouette: "어깨형",
    proportion: "밸런스",
    frame: "와이드",
    tops: ["D", "E", "C", "D", "B", "D", "C", "E", "B", "C", "C", "E", "D", "B", "B", "C", "E", "B", "B", "B", "B", "E", "B", "C", "E", "C", "D", "D", "E", "B", "B", "C", "B", "B", "A", "B", "B", "B", "C", "D"],
    bots: ["B", "C", "C", "E", "B", "B", "B", "C", "B", "E", "B", "C", "A", "C", "A", "B", "B", "C", "B", "D", "E", "C", "A", "A", "D"],
    topBest: 34,
    botBest: 12,
  },
  {
    skeleton: "웨이브",
    silhouette: "어깨형",
    proportion: "롱토르소",
    frame: "슬림",
    tops: ["B", "C", "A", "C", "A", "B", "A", "C", "A", "A", "A", "C", "C", "B", "A", "B", "C", "A", "B", "A", "A", "C", "D", "D", "C", "A", "C", "B", "C", "A", "A", "A", "A", "A", "C", "D", "D", "A", "B", "C"],
    bots: ["D", "B", "B", "C", "C", "C", "C", "B", "D", "C", "D", "B", "B", "C", "A", "D", "D", "C", "D", "D", "C", "C", "A", "B", "D"],
    topBest: 17,
    botBest: 14,
  },
  {
    skeleton: "웨이브",
    silhouette: "어깨형",
    proportion: "롱토르소",
    frame: "미디엄",
    tops: ["B", "C", "B", "D", "B", "C", "B", "D", "B", "B", "B", "C", "D", "B", "B", "C", "C", "A", "B", "B", "B", "C", "D", "D", "C", "B", "C", "C", "C", "A", "B", "A", "A", "A", "C", "C", "C", "A", "B", "D"],
    bots: ["C", "B", "B", "D", "B", "B", "B", "B", "C", "D", "C", "B", "B", "C", "A", "C", "C", "C", "C", "D", "D", "C", "A", "B", "D"],
    topBest: 17,
    botBest: 14,
  },
  {
    skeleton: "웨이브",
    silhouette: "어깨형",
    proportion: "롱토르소",
    frame: "와이드",
    tops: ["C", "D", "C", "D", "B", "D", "C", "E", "B", "C", "C", "D", "D", "C", "B", "C", "D", "B", "C", "B", "B", "D", "C", "D", "D", "C", "D", "D", "D", "B", "B", "B", "B", "B", "B", "C", "C", "B", "C", "D"],
    bots: ["B", "C", "C", "E", "B", "B", "B", "C", "B", "E", "B", "C", "A", "C", "A", "B", "B", "C", "C", "E", "E", "C", "A", "A", "E"],
    topBest: 17,
    botBest: 14,
  },
  {
    skeleton: "웨이브",
    silhouette: "밸런스",
    proportion: "롱레그",
    frame: "슬림",
    tops: ["B", "B", "B", "A", "B", "B", "B", "A", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "C", "B", "C", "B", "B", "B", "B", "B", "B", "B", "B", "B", "C", "B", "C", "C", "C", "B", "B"],
    bots: ["C", "B", "B", "A", "C", "C", "C", "B", "C", "A", "C", "B", "B", "B", "B", "C", "C", "B", "C", "A", "A", "B", "B", "B", "A"],
    topBest: 3,
    botBest: 9,
  },
  {
    skeleton: "웨이브",
    silhouette: "밸런스",
    proportion: "롱레그",
    frame: "미디엄",
    tops: ["C", "C", "B", "A", "B", "B", "C", "A", "B", "B", "B", "C", "B", "B", "B", "B", "B", "C", "B", "B", "B", "C", "B", "B", "B", "B", "B", "B", "B", "C", "B", "C", "C", "C", "B", "B", "B", "C", "C", "B"],
    bots: ["B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B"],
    topBest: 3,
    botBest: 9,
  },
  {
    skeleton: "웨이브",
    silhouette: "밸런스",
    proportion: "롱레그",
    frame: "와이드",
    tops: ["D", "D", "C", "B", "B", "C", "D", "C", "B", "C", "C", "D", "C", "B", "B", "B", "D", "C", "B", "B", "B", "D", "A", "B", "C", "C", "C", "C", "C", "C", "B", "D", "C", "C", "A", "B", "B", "C", "C", "B"],
    bots: ["B", "C", "C", "C", "B", "B", "B", "C", "B", "C", "B", "C", "A", "B", "B", "B", "B", "C", "B", "B", "C", "B", "B", "B", "B"],
    topBest: 22,
    botBest: 12,
  },
  {
    skeleton: "웨이브",
    silhouette: "밸런스",
    proportion: "밸런스",
    frame: "슬림",
    tops: ["B", "B", "B", "A", "B", "B", "B", "A", "B", "B", "B", "B", "B", "B", "B", "B", "A", "B", "B", "B", "B", "B", "C", "C", "A", "B", "A", "B", "A", "B", "B", "B", "B", "B", "C", "D", "D", "B", "B", "B"],
    bots: ["C", "B", "B", "B", "C", "C", "C", "B", "C", "B", "C", "B", "B", "B", "B", "C", "C", "B", "C", "B", "B", "B", "B", "B", "B"],
    topBest: 3,
    botBest: 1,
  },
  {
    skeleton: "웨이브",
    silhouette: "밸런스",
    proportion: "밸런스",
    frame: "미디엄",
    tops: ["B", "B", "B", "A", "B", "B", "B", "A", "B", "B", "B", "B", "B", "B", "B", "B", "A", "B", "B", "B", "B", "B", "B", "B", "A", "B", "A", "B", "A", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B"],
    bots: ["B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B"],
    topBest: 3,
    botBest: 1,
  },
  {
    skeleton: "웨이브",
    silhouette: "밸런스",
    proportion: "밸런스",
    frame: "와이드",
    tops: ["C", "C", "C", "B", "B", "C", "C", "C", "B", "C", "C", "C", "C", "B", "B", "B", "C", "B", "B", "B", "B", "C", "B", "B", "C", "C", "B", "C", "C", "B", "B", "C", "B", "B", "B", "B", "B", "B", "B", "B"],
    bots: ["B", "C", "C", "D", "B", "B", "B", "C", "B", "C", "B", "C", "B", "C", "B", "B", "B", "C", "B", "C", "C", "C", "B", "B", "C"],
    topBest: 22,
    botBest: 12,
  },
  {
    skeleton: "웨이브",
    silhouette: "밸런스",
    proportion: "롱토르소",
    frame: "슬림",
    tops: ["A", "A", "B", "A", "B", "B", "A", "A", "B", "B", "B", "A", "B", "B", "B", "B", "A", "A", "B", "B", "B", "A", "D", "C", "A", "B", "A", "B", "A", "A", "B", "A", "A", "A", "D", "E", "E", "A", "A", "B"],
    bots: ["D", "B", "B", "B", "C", "C", "C", "B", "D", "B", "D", "B", "B", "C", "B", "D", "D", "C", "D", "C", "B", "C", "B", "B", "C"],
    topBest: 16,
    botBest: 1,
  },
  {
    skeleton: "웨이브",
    silhouette: "밸런스",
    proportion: "롱토르소",
    frame: "미디엄",
    tops: ["B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "C", "B", "B", "B", "A", "B", "B", "B", "B", "B", "C", "C", "A", "B", "A", "B", "A", "B", "B", "B", "B", "B", "C", "D", "D", "B", "B", "B"],
    bots: ["C", "B", "B", "C", "B", "B", "B", "B", "C", "B", "C", "B", "B", "C", "B", "C", "C", "C", "D", "C", "B", "C", "B", "B", "C"],
    topBest: 16,
    botBest: 1,
  },
  {
    skeleton: "웨이브",
    silhouette: "밸런스",
    proportion: "롱토르소",
    frame: "와이드",
    tops: ["C", "C", "D", "B", "C", "D", "C", "C", "C", "D", "D", "C", "C", "C", "C", "C", "B", "B", "C", "C", "C", "C", "C", "B", "B", "D", "B", "D", "B", "B", "C", "C", "B", "B", "C", "C", "C", "B", "B", "C"],
    bots: ["C", "C", "C", "D", "B", "B", "B", "C", "C", "D", "C", "C", "B", "C", "B", "C", "C", "C", "C", "D", "D", "C", "B", "B", "D"],
    topBest: 26,
    botBest: 14,
  },
  {
    skeleton: "웨이브",
    silhouette: "곡선형",
    proportion: "롱레그",
    frame: "슬림",
    tops: ["B", "C", "B", "B", "B", "B", "B", "B", "A", "B", "B", "C", "B", "B", "B", "B", "C", "B", "B", "A", "A", "C", "B", "C", "C", "A", "C", "C", "C", "B", "A", "B", "B", "C", "B", "C", "C", "C", "B", "B"],
    bots: ["E", "B", "B", "A", "E", "E", "E", "B", "E", "A", "E", "B", "B", "B", "B", "E", "E", "B", "E", "A", "A", "B", "B", "B", "A"],
    topBest: 8,
    botBest: 9,
  },
  {
    skeleton: "웨이브",
    silhouette: "곡선형",
    proportion: "롱레그",
    frame: "미디엄",
    tops: ["C", "C", "B", "B", "B", "B", "C", "B", "A", "B", "B", "C", "B", "B", "B", "B", "C", "B", "B", "A", "A", "C", "B", "C", "C", "A", "C", "C", "C", "C", "A", "B", "B", "C", "B", "B", "B", "C", "C", "B"],
    bots: ["D", "B", "B", "B", "D", "D", "D", "B", "D", "B", "D", "B", "B", "B", "B", "D", "D", "B", "D", "B", "B", "B", "B", "B", "B"],
    topBest: 8,
    botBest: 9,
  },
  {
    skeleton: "웨이브",
    silhouette: "곡선형",
    proportion: "롱레그",
    frame: "와이드",
    tops: ["D", "D", "C", "C", "B", "C", "D", "D", "B", "C", "C", "D", "C", "B", "B", "B", "E", "C", "B", "B", "B", "E", "A", "B", "D", "C", "D", "E", "D", "C", "B", "C", "C", "C", "A", "A", "A", "C", "C", "C"],
    bots: ["D", "C", "C", "C", "D", "D", "D", "C", "D", "C", "D", "C", "A", "C", "B", "D", "D", "C", "C", "B", "C", "C", "B", "B", "B"],
    topBest: 35,
    botBest: 12,
  },
  {
    skeleton: "웨이브",
    silhouette: "곡선형",
    proportion: "밸런스",
    frame: "슬림",
    tops: ["B", "B", "B", "B", "B", "B", "B", "B", "A", "B", "B", "B", "B", "B", "B", "B", "B", "A", "B", "A", "A", "B", "C", "C", "B", "A", "B", "C", "B", "B", "A", "A", "A", "B", "C", "C", "C", "B", "B", "B"],
    bots: ["E", "B", "B", "B", "E", "E", "E", "B", "E", "B", "E", "B", "B", "C", "B", "E", "E", "B", "E", "B", "B", "C", "B", "B", "B"],
    topBest: 8,
    botBest: 1,
  },
  {
    skeleton: "웨이브",
    silhouette: "곡선형",
    proportion: "밸런스",
    frame: "미디엄",
    tops: ["B", "B", "B", "B", "B", "B", "B", "B", "A", "B", "B", "B", "B", "B", "B", "B", "B", "A", "B", "A", "A", "B", "B", "C", "B", "A", "B", "C", "B", "B", "A", "A", "A", "B", "B", "B", "B", "B", "B", "B"],
    bots: ["D", "B", "B", "B", "D", "D", "D", "B", "D", "B", "D", "B", "B", "C", "B", "D", "D", "B", "D", "B", "B", "C", "B", "B", "B"],
    topBest: 8,
    botBest: 1,
  },
  {
    skeleton: "웨이브",
    silhouette: "곡선형",
    proportion: "밸런스",
    frame: "와이드",
    tops: ["C", "D", "C", "C", "B", "C", "C", "D", "B", "C", "C", "D", "C", "B", "B", "B", "D", "B", "B", "B", "B", "D", "B", "B", "D", "C", "C", "E", "D", "B", "B", "C", "B", "B", "B", "B", "B", "B", "B", "C"],
    bots: ["D", "C", "C", "D", "D", "D", "D", "C", "D", "C", "D", "C", "B", "C", "B", "D", "D", "C", "D", "C", "C", "C", "B", "B", "C"],
    topBest: 35,
    botBest: 12,
  },
  {
    skeleton: "웨이브",
    silhouette: "곡선형",
    proportion: "롱토르소",
    frame: "슬림",
    tops: ["A", "B", "B", "B", "B", "B", "A", "B", "A", "B", "B", "B", "B", "B", "B", "B", "B", "A", "B", "A", "A", "B", "D", "C", "B", "A", "B", "C", "B", "A", "A", "A", "A", "A", "D", "D", "D", "A", "A", "B"],
    bots: ["E", "B", "B", "B", "E", "E", "E", "B", "E", "B", "E", "B", "B", "C", "B", "E", "E", "C", "E", "C", "B", "C", "B", "B", "C"],
    topBest: 17,
    botBest: 1,
  },
  {
    skeleton: "웨이브",
    silhouette: "곡선형",
    proportion: "롱토르소",
    frame: "미디엄",
    tops: ["B", "B", "B", "C", "B", "B", "B", "C", "B", "B", "B", "B", "C", "B", "B", "B", "B", "A", "B", "B", "B", "B", "C", "C", "B", "B", "B", "D", "B", "B", "B", "A", "A", "B", "C", "C", "C", "B", "B", "C"],
    bots: ["E", "B", "B", "C", "D", "D", "D", "B", "E", "B", "E", "B", "B", "C", "B", "E", "E", "C", "E", "C", "B", "C", "B", "B", "C"],
    topBest: 17,
    botBest: 1,
  },
  {
    skeleton: "웨이브",
    silhouette: "곡선형",
    proportion: "롱토르소",
    frame: "와이드",
    tops: ["C", "C", "D", "C", "C", "D", "C", "D", "B", "D", "D", "C", "C", "C", "C", "C", "C", "B", "C", "B", "B", "C", "C", "C", "C", "C", "C", "E", "C", "B", "B", "B", "B", "B", "C", "C", "C", "B", "B", "C"],
    bots: ["D", "C", "C", "D", "D", "D", "D", "C", "D", "D", "D", "C", "B", "C", "B", "D", "D", "C", "E", "D", "D", "C", "B", "B", "D"],
    topBest: 17,
    botBest: 14,
  },
];

// 등급 → 점수
export const GRADE_SCORE: Record<Grade, number> = { A: 2, B: 1, C: 0, D: -1, E: -2 };

// 4축 lookup
export function lookupMatrix(s: Skeleton, sil: Silhouette, p: Proportion, f: Frame): MatrixEntry | undefined {
  return BODY_MATRIX.find((m) => m.skeleton === s && m.silhouette === sil && m.proportion === p && m.frame === f);
}
